- build/csw_components/_login-bar.scss
- build/gulp_tasks/6.environment.database.js
- chalice/app.py
- chalice/chalicelib/auth.py
- chalice/chalicelib/database_handle.py
- chalice/chalicelib/demos.py
- chalice/chalicelib/models.py
- chalice/chalicelib/routes.py
- chalice/chalicelib/template_handler.py
- chalice/chalicelib/templates/govuk_template.html
- chalice/chalicelib/templates/not_found.html
- chalice/chalicelib/templates/request_access.html
- chalice/chalicelib/test_auth.py
Login status was being retained by re-used lambdas: CT-298
The login was open to anyone on our email domain and is now restricted to known users: CT-136
Two new models have been added User and UserSession. You can destroy and recreate your env or just run the following to add the new tables: 
`aws-vault exec cst-test -- aws lambda invoke --function-name csw-[env]-database_create_tables --payload '{"Tables":["User", "UserSession"]}' /tmp/lambda.out`
To create a user fill in the blanks and run the following:
`aws lambda invoke --function-name csw-[env]-database_create_item --payload '{"Model":"User","Params":{"email": "[email@address]", "name": "[Firstname Surname]", "active": true}}' /tmp/lambda.out` to create a user. 
The template handler used to be called with the route path on method …
> Refactor authentication and template handling

- build/csw_components/_5cols.scss
- chalice/chalicelib/templates/components/check_results.html
A couple of lines.
Quick overview of changes:
* Created a new css colour component using `govuk-colour("grey-1")`
* Used an `{% if %}` in the `check_results` template to check if `item.failed` is nonzero, and use the either the `--failed` or `--nonefailed` colour accordingly
Here's a preview:
> CT-349 Turn issue backgrounds grey/white where the count is 0

- chalice/chalicelib/aws/gds_iam_client.py
It wasn't used so far so this change won't break anything, but it
wouldn't have worked in its current state (list_users doesn't output a
dictionary with a 'Roles' key). Hopefully I'll be using this method
soon.
> Fixed the method in the IAM client for list_roles

- chalice/chalicelib/aws/gds_iam_client.py
Moving the iam = self.get_boto3_session_client('iam', session) into __init__ breaks stuff. We should move it back one day, but not right now.
> Revert GdsIamClient change

- build/sql/definition/00006.sql
- chalice/chalicelib/audit.py
- chalice/chalicelib/criteria/criteria_default.py
- chalice/chalicelib/models.py
- chalice/chalicelib/utilities.py
I've added a method to the utilities class to log the type and module of an exception with the exception string so it's more helpful. I've had to add the resource name and id temporarily to the raw data for the summarise method but this is fixed properly in the next branch (any_checks)
> Implement resource_persistent_id field in audit_resource which should survive re-terraforming

- chalice/chalicelib/audit.py
- chalice/chalicelib/criteria/aws_iam_roles_with_trust_relationship.py
- chalice/chalicelib/criteria/criteria_default.py
This is primarily for the IAM "At least one role trusts a user from gds-users" check but there are other use-cases where any compliant resource can be a pass.
> Add "any" | "all" option to check classes so we can have checks which pass when any single resource passes. 

- chalice/chalicelib/aws/gds_s3_client.py
- chalice/chalicelib/criteria/aws_s3_versioning.py
- chalice/tests/chalicelib/criteria/test_aws_s3_versioning.py
- chalice/tests/chalicelib/criteria/test_data.py
Summary of changes:
- Added a new method to the S3 client, implementing the get_bucket_versioning API call. This requires an update of the CSW client role, otherwise the check will run into access denied errors.
- Unit tests and test data added for the check
- This includes a test for when a `COMPLIANT` resource follows a `NON_COMPLIANT` one. We found out that because we use the same instance of the criteria class when evaluating a list of resources, the `annotation` field of the instance remains after being set by a failing resource - meaning that in CloudWatch logs, a `COMPLIANT` evaluation also includes a failing annotation, which is incredibly confusing. We fixed this with the line `self.annotation = ""` when a resource passes the check. More work needs to be done to both fix this for …
> S3 versioning

- chalice/chalicelib/aws/gds_aws_client.py
The verify account ID has a leading zero and without that the ARN is not recognised for the assume role.
> CT-593 - Left pad AWS account ID with 0s up to 12 characters.

- chalice/chalicelib/criteria/aws_s3_secure_policy.py
- chalice/tests/chalicelib/criteria/test_aws_s3_secure_policy.py
- chalice/tests/chalicelib/criteria/test_data.py
This is to fix the criterion as it did too much - it was only supposed to check if the aws:SecureTransport condition existed in a policy, not whether it was set to true or false.
(Background: aws:SecureTransport represents whether a connection to the bucket was made using HTTPS. It is set to true if HTTPS was used, false if not.)
This is because it is possible to have a secure bucket policy by using the condition's false status to *deny* access to the bucket, which I didn't consider. However, the previous version of the evaluate method in the criterion would have failed such a policy.
It may be a good idea to re-work this check again in the future, by having the evaluate method look at the policy in greater detail to make sure that access is being allowed or denied for the correct values …
> [CT-500] S3 HTTPS policy fix

- build/sql/definition/00014.sql
- chalice/chalicelib/audit.py
- chalice/chalicelib/models.py
Each audit_criterion is marked as attempted=True even if it is not successfully processed. 
This means we can then mark an audit as finished when every check has been attempted even if it is not complete (every check has been successfully processed). 
The latest audit is then the most recent "finished" audit rather than the most recent "completed" audit.
> CT-616 - Label an audit finished even if it is not complete. 

- chalice/chalicelib/criteria/aws_iam_validate_inspector_policy.py
- chalice/chalicelib/criteria/aws_vpc_flow_logs_enabled.py
IAM Inspector role: is_regional = False
VPC flow log check: active = False - since we don't have the DescribeVpcs permission in the client role
> CT-633 - Correct is_regional and active settings on checks

- chalice/chalicelib/audit.py
Currently the next step of the audit can start running as soon as the first SQS message is written so it sometimes starts before the active criteria count is set.
> CT-632 - Save audit as soon as active criteria count are set.

- chalice/chalicelib/test_auth.py
- chalice/tests/chalicelib/criteria/test_aws_vpc_flow_logs_enabled.py
AuthHandler and AwsVpcFlowLogsEnabled tests are broken. We need to
have the test suite working for https://govukverify.atlassian.net/browse/CT-657
> Disable broken tests

- build/gulp_helpers/helpers.js
- build/gulp_tasks/9.1.test.tasks.js
.. so that a behave scenario fails the gulp pipeline completes (credentials are
rotated and disabled) but the response code from gulp is set to the
exit code from the behave task.
> Pass exit code from task helper and implement in e2e task

- chalice/requirements-dev.txt
- chalice/requirements.txt
Not a lot of very significant changes. For each update, I made sure that:
- All unit tests passed
- `gulp environment.redeploy` runs and completes
- A manual account audit completes
There are two things to note here:
- After all of these updates, there are still 4 packages that are marked as outdated: `attrs`, `click`, `pip` and `typing`. These are all due to the most current version of Chalice requiring them to be a certain version, which can be seen here: https://github.com/aws/chalice/blob/master/setup.py
- When running `pip install -r requirements-dev.txt`, there is an "error", with the message `ERROR: botocore 1.12.154 has requirement urllib3<1.25,>=1.20; python_version >= "3.4", but you'll have urllib3 1.25.2 which is incompatible.` This is due to botocore devs not properly updating …
> [CT-341] Update pip packages

- build/sql/definition/00015.sql
- chalice/chalicelib/audit.py
Remove duplicate records from audit_criterion.
Update account_audit records from remaining audit_criterion records.
Create unique constraint on audit_criterion table (account_audit_id,criterion_id)
Add try catch in audit to catch key errors on duplicate key constraints.
> CT-692: Deal with SQS messages being processed twice by the evaluate criteria lambda

- chalice/tests/chalicelib/criteria/test_criteria_default.py
Changed to check active is set and is boolean.
> CT-735 - Correct unittest which assumed the active state of all checks must be True

- chalice/chalicelib/api/derived_stats_tables/11_resources.sql
Currently there's a bug in the script parser which treats a blank line in a SQL statement as 2 separate queries.
> CT-726c - Remove blank line in statement due to bug in script parser

- build/sql/definition/00100.sql
- chalice/chalicelib/api/derived_stats_tables/00_current_coverage_stats.sql
- chalice/chalicelib/api/derived_stats_tables/02_current_summary_stats.sql
- chalice/chalicelib/api/derived_stats_tables/05_daily_summary_stats.sql
- chalice/chalicelib/api/derived_stats_tables/07_monthly_summary_stats.sql
- chalice/chalicelib/audit.py
- chalice/chalicelib/aws/gds_organizations_client.py
- chalice/chalicelib/aws/gds_ssm_client.py
- chalice/chalicelib/models.py
- chalice/chalicelib/utilities.py
Subscriptions are updated by running organization list-accounts against the parent account and set to annotated with auditable, suspended properties so we can differentiate between closed accounts and live accounts we can't audit.
> CT-728 - Switch to automated account subscription updates

- build/gulp_tasks/4.environment.terraform.js
This is so we can remove the expect script as part of the concourse
pipeline. This was swallowing errors.
> Add bastion and dev box to known hosts.

- chalice/chalicelib/utilities.py
- chalice/requirements-dev.txt
- chalice/tests/chalicelib/test_utilities.py
Tracebacks outputted using the default formatter are multiline
events. This makes it difficult to reconstruct using Cloudwatch
insights as logs from multiple lambdas are interleaved. Changing
output format to JSON makes it easier to search for, and debug
exceptions.
> Change tracebacks output from multiline-text to JSON.

- chalice/chalicelib/api.py
- chalice/chalicelib/audit.py
- chalice/chalicelib/aws/gds_aws_client.py
- chalice/chalicelib/aws/gds_s3_client.py
- chalice/chalicelib/controllers.py
- chalice/chalicelib/criteria/aws_cloudtrail_log_validation.py
- chalice/chalicelib/criteria/aws_cloudtrail_multiregional.py
- chalice/chalicelib/criteria/aws_ebs_encryption.py
- chalice/chalicelib/criteria/aws_kms_managed_cmk_rotation.py
- chalice/chalicelib/criteria/aws_rds_encryption.py
- chalice/chalicelib/models.py
- chalice/chalicelib/routes.py
- chalice/chalicelib/utilities.py
For Exceptions using the `.get_typed_exception()` helper. The method
signature has been updated to not pass the `err` through to the
function as that is found by searching the current stack. I've also
changed the logging level to be `error` consistently.
> Make exception handling consistent.

- chalice/chalicelib/auth.py
- chalice/tests/chalicelib/test_auth.py
auth.py:414  self.google_token = flow.fetch_token(code=code)
Logging in with OAuth was breaking on the above code due to the Google
OAuth scopes having been updated. The following error was being
generated but swallowed by the exception handling.
Scope has changed from "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email" to "openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email".
> Update OAuth scopes with "openid"

- chalice/chalicelib/api/derived_stats_tables/11_resources.sql
This is a quick fix to make the health data work in production. 
It breaks the historic trend data but at the moment we're not using that. 
I've raised CT-806 to come up with a new query to calculate the historic trend more efficiently.
> CT-805 - Limit the _resources table to results from the past 28 days.

- chalice/chalicelib/models.py
Add default return string to tags.get to ensure lower method is available on the result.
> CT-803 - Fix IAM role filtering - failing on tags.get with no default return value.

- chalice/chalicelib/api/derived_stats_tables/01_current_account_stats.sql
- chalice/chalicelib/api/derived_stats_tables/04_daily_account_stats.sql
- chalice/chalicelib/api/derived_stats_tables/06.5_daily_resource_count.sql
- chalice/chalicelib/api/derived_stats_tables/11_resources.sql
- chalice/chalicelib/templates/components/charts/stats_current_account_percent_failure.html
We need this change to measure the value we've added through hiding the non-sev-1 errors from the interface.
> CSW-50 - Update derived stats tables to reference only sev 1 failures

- chalice/chalicelib/aws/gds_ec2_security_group_client.py
- chalice/chalicelib/aws/gds_s3_client.py
- chalice/chalicelib/aws/gds_support_client.py
- chalice/chalicelib/criteria/aws_support_rds_security_groups.py
- chalice/chalicelib/criteria/aws_support_s3_bucket_permissions.py
- chalice/chalicelib/criteria/criteria_default.py
I've made a few changes here: 
1. The trusted advisor check get_data method now does a looped retry to refresh the check status to ensure we have current data. I've added a max retry count so it doesn't keep refreshing forever. It's also has a non-actioned except because some TA checks raise a "not refreshable" exception.
2. Add a get_resource_data method to the TA checks to get the raw data associated with the failing resources - This is overridden per check so it doesn't fail if not implemented in a given check.
3. Change the annotation and how_do_i_fix_it entries for the 2 checks mentioned.
> CSW-53&67 - Improve text for S3 ACL and RDS classic security group checks

- chalice/chalicelib/criteria/aws_ec2_security_group_ingress_ssh.py
- chalice/tests/chalicelib/aws/test_client_default.py
- chalice/tests/chalicelib/criteria/test_criteria_default.py
- chalice/tests/chalicelib/test_auth.py
- chalice/tests/chalicelib/test_template_handler.py
CloudSecurityWatch sub class rather than native Chalice.
+ declare a default return list for valid ranges for unittest mode
> CSW-78 - Switch unit test classes to declare app as an instance of the

- chalice/chalicelib/criteria/aws_kms_managed_cmk_rotation.py
Based on #158 
I ran this through `black` so no worries there. This change doesn't touch any logic so any tests should pass/fail as before.
> Fix poor explanations in KMS check

- chalice/chalicelib/audit.py
The scheduled lambda is currently failing because it's invoked without the context parameter from the schedule.
> Remove context from subs schedule

- build/gulp_helpers/helpers.js
- build/package-lock.json
- build/package.json
- chalice/chalicelib/admin.py
- chalice/chalicelib/api/derived_stats_tables/07_daily_account_audits.sql
- chalice/chalicelib/api/derived_stats_tables/11_daily_resource_count.sql
Create a scheduled lambda to delete expired audits (> 1 year old)
+ manual invoke method for testing.
Change stats queries to generate static stats for past 3 months. 
and some version upgrades in the package file
> Limit stats history
