.gitignore
README.md
environments/example/.chalice/config.json

I've added an example .chalice/config.json and instructions in the readme for creating your own chalice config and symlinking it into the chalice folder.

Config readme

---

build/cloud-security-watch-ie8.scss
build/cloud-security-watch.scss
build/csw_components/_login-bar.scss
build/csw_components/_team-list.scss
chalice/app.py
chalice/chalicelib/auth.py
chalice/chalicelib/aws/gds_aws_client.py
chalice/chalicelib/collator.py
chalice/chalicelib/demos.py
chalice/chalicelib/route.py
chalice/chalicelib/template_handler.py
chalice/chalicelib/templates/audit.html
chalice/chalicelib/templates/audit_list.html
chalice/chalicelib/templates/components/check_results.html
chalice/chalicelib/templates/components/failed_resources.html
chalice/chalicelib/templates/components/header.html
chalice/chalicelib/templates/components/logged_in.html
chalice/chalicelib/templates/components/resource_compliance.html
chalice/chalicelib/templates/components/team_list.html
chalice/chalicelib/templates/components/team_stats.html
chalice/chalicelib/templates/govuk_template.html
chalice/chalicelib/templates/logged_in.html
chalice/chalicelib/templates/logged_out.html
chalice/chalicelib/templates/overview.html
chalice/chalicelib/templates/resource_details.html
chalice/chalicelib/templates/team_dashboard.html
chalice/chalicelib/templates/teams.html
chalice/chalicelib/templates/test_evaluation.html

This is the content to-date for the front-end routes, oauth and some more refactoring to *hopefully* make the code easier to read.

Dashboards

---

README.md
chalice/chalicelib/criteria/test_criteria_default.py

Just testing the unit test setup

setting up unit testing

---

README.md
chalice/chalicelib/criteria/criteria_default.py
chalice/chalicelib/criteria/test_criteria_default.py

Please review in particular the two changes in the CriteriaDefault class.

More meaningful default criteria tests

---

build/gulp_tasks/0.parameters.shared.js
build/gulp_tasks/6.environment.database.js
chalice/chalicelib/audit.py
chalice/chalicelib/aws/gds_aws_client.py
chalice/chalicelib/models.py
chalice/chalicelib/routes.py
chalice/chalicelib/template_handler.py
chalice/chalicelib/templates/components/team_stats.html
chalice/chalicelib/templates/server_error.html

Correct the gulp shared parameters to load the shared google auth and terraform backend S3 settings. Fixed bugs CT-295 and CT-297. Corrected the URL to the new GDS wiki page for the public IPs. Added a server_error template to render an HTML response on exception.

Setup production account. 

---

chalice/chalicelib/templates/components/intro.html

Fixed the link

---

chalice/chalicelib/criteria/aws_iam_roles_with_trust_relationship.py
chalice/tests/chalicelib/criteria/test_aws_iam_roles_with_trust_relationship.py
chalice/tests/chalicelib/criteria/test_criteria_default.py
chalice/tests/chalicelib/criteria/test_data.py

I deleted the account number that we will be checking against. I will be
changing it back on my local branch. Hopefully we will figure out a way
of defining the "main account" (or whatever we'll call it) soon.

Initial commit for IAM Roles with trust relationship check

---

chalice/chalicelib/criteria/aws_iam_roles_with_trust_relationship.py
chalice/tests/chalicelib/criteria/test_aws_iam_roles_with_trust_relationship.py
chalice/tests/chalicelib/criteria/test_data.py

Hi, this should be the finished version of this criterion. If anyone has any questions please ask

IAM Roles with trust relationship criterion

---

.gitignore
build/gulp_helpers/helpers.js
build/gulp_helpers/psql_tunnel.py
build/gulp_tasks/6.environment.database.js
build/gulp_tasks/9.build.tasks.js
build/sql/definition/00001.sql
build/sql/definition/00002.sql
build/sql/definition/00003.sql
chalice/chalicelib/auth.py
chalice/chalicelib/database_handle.py
chalice/chalicelib/models.py
chalice/chalicelib/routes.py
chalice/chalicelib/template_handler.py
chalice/chalicelib/templates/components/refused.html
chalice/chalicelib/templates/denied.html

I've implemented a simple framework for handling database changes. It stores an index of changes in a _metadata_version table in the database which the first script defines. It then runs any subsequent scripts that have been added since the current indexed version. I've separated schema changes from data changes so we can use the same method to populate the database from a private repo. I've also implemented in here a model for linking users to teams. ProductTeamUser and denied templates when the user does not have access.

Memberships and migrations

---

chalice/chalicelib/criteria/aws_s3_secure_policy.py
chalice/tests/chalicelib/criteria/test_aws_s3_secure_policy.py

This fixes the translate method of the S3 Bucket HTTPS check I PRed yesterday, and also fixes a typo in that check because why not.
2 lines.

Build eval fix

---

chalice/chalicelib/aws/gds_cloudtrail_client.py
chalice/chalicelib/criteria/aws_cloudtrail_multiregional.py
chalice/chalicelib/criteria/aws_kms_managed_cmk_rotation.py
chalice/chalicelib/criteria/aws_support_cloudtrail_logging.py
chalice/tests/chalicelib/criteria/test_aws_cloudtrail_multiregional.py
chalice/tests/chalicelib/criteria/test_aws_support_cloudtrail_logging.py
chalice/tests/chalicelib/criteria/test_data.py

new check and deactivating similar TA check

Multiregional cloudtrail

---

chalice/chalicelib/aws/gds_ec2_client.py
chalice/chalicelib/criteria/aws_kms_managed_cmk_rotation.py
chalice/chalicelib/criteria/aws_vpc_flow_logs_enabled.py
chalice/chalicelib/database_handle.py
chalice/tests/chalicelib/criteria/test_aws_vpc_flow_logs_enabled.py
chalice/tests/chalicelib/criteria/test_data.py

Run twice successfully on UAT.

Vpc flow enabled

---

chalice/chalicelib/criteria/aws_s3_secure_policy.py

I couldn't find anything on google for `aws:SecureTransports3bucket`
but the linked blog post talked about `aws:SecureTransport` which I
believe is what is required here?

fix condition variable documentation

---

chalice/chalicelib/aws/gds_s3_client.py
chalice/chalicelib/criteria/aws_s3_default_encryption_at_rest.py
chalice/tests/chalicelib/criteria/test_aws_s3_default_encryption_at_rest.py
chalice/tests/chalicelib/criteria/test_data.py

This passes all the unit tests. I've deployed on UAT and it completes successfully, with all the resources correctly passing/failing.
Related `csw-client-role` PR: https://github.com/alphagov/csw-client-role/pull/20

[CT-591] S3 encryption at rest

---

chalice/chalicelib/auth.py
chalice/chalicelib/criteria/aws_ec2_egress_restriction.py
chalice/chalicelib/criteria/aws_iam_roles_with_trust_relationship.py
chalice/chalicelib/criteria/aws_iam_validate_inspector_policy.py
chalice/chalicelib/criteria/aws_s3_default_encryption_at_rest.py
chalice/chalicelib/criteria/aws_support_access_key_exposed.py
chalice/chalicelib/criteria/aws_support_access_key_rotation.py
chalice/chalicelib/criteria/aws_support_cloudtrail_logging.py
chalice/chalicelib/criteria/aws_support_ebs_public_snapshots.py
chalice/chalicelib/criteria/aws_support_elb_listener_security.py
chalice/chalicelib/criteria/aws_support_elb_security_groups.py
chalice/chalicelib/criteria/aws_support_rds_public_snapshots.py
chalice/chalicelib/criteria/aws_support_rds_security_groups.py
chalice/chalicelib/criteria/aws_support_root_mfa.py
chalice/chalicelib/criteria/aws_support_s3_bucket_permissions.py
chalice/chalicelib/criteria/aws_vpc_flow_logs_enabled.py
chalice/chalicelib/models.py
chalice/chalicelib/routes.py
chalice/chalicelib/template_handler.py
chalice/chalicelib/templates/audit_status.html
chalice/chalicelib/templates/check_issues.html
chalice/chalicelib/templates/check_status_resources.html
chalice/chalicelib/templates/components/audit_check_resources_list.html
chalice/chalicelib/templates/components/audit_check_status.html
chalice/chalicelib/templates/components/audit_header.html
chalice/chalicelib/templates/components/audit_resource_categories.html
chalice/chalicelib/templates/components/audit_status.html
chalice/chalicelib/templates/components/check_header.html

CT-619 - Changes to account status and audit results pages

---

build/gulp_helpers/helpers.js
build/gulp_tasks/0.parameters.shared.js
build/gulp_tasks/1.environment.settings.js
build/gulp_tasks/2.environment.params.js
build/gulp_tasks/3.environment.tfvars.js
build/gulp_tasks/4.environment.terraform.js
build/gulp_tasks/5.environment.chalice.js
build/gulp_tasks/6.environment.database.js
build/gulp_tasks/7.copy.assets.js
build/gulp_tasks/8.sass.js
build/gulp_tasks/9.1.test.tasks.js
build/gulp_tasks/9.build.tasks.js
build/gulpfile.js

Prettier the code

---

build/gulp_tasks/6.environment.database.js

I've added a final promise which only resolves once all the migrations have run which means that the gulp task now waits to complete until the migrations have completed.

Do not return from migrations task until the scripts have run

---

chalice/chalicelib/criteria/aws_iam_validate_inspector_policy.py
chalice/chalicelib/criteria/aws_s3_default_encryption_at_rest.py
chalice/chalicelib/criteria/aws_s3_secure_policy.py
chalice/chalicelib/criteria/aws_support_access_key_rotation.py
chalice/chalicelib/criteria/aws_vpc_flow_logs_enabled.py

+ switch of IAM key rotation @90days check 
+ correct NOT_COMPLIANT to NON_COMPLIANT in 3 checks.

CT-735 - Switch off inspector role check

---

build/gulp_tasks/0.parameters.shared.js
build/gulp_tasks/1.environment.settings.js
build/gulp_tasks/3.environment.tfvars.js
chalice/app.py
chalice/chalicelib/audit.py
chalice/chalicelib/aws/gds_aws_client.py
chalice/chalicelib/criteria/criteria_default.py

Change the assume mechanism to assume the chain role in the billing account and then the security audit role in the target account.

CT-720: Switch to using the GDSSecurityAudit role in evaluate criteria lambda

---

chalice/chalicelib/api/derived_stats_tables/10_prevous_next_resource_stats.sql
chalice/chalicelib/api/derived_stats_tables/11_previous_next_resource_status_stats.sql
chalice/chalicelib/api/health_metric_queries/csw_average_failing_resource_days.sql
chalice/chalicelib/api/health_metric_queries/csw_percentage_actioned_resources.sql

They should run successfully on production for now but we may need to revisit as we onboard more
accounts

CT-726 - Stats helper tables - These are better but still not great. 

---

chalice/chalicelib/api/derived_stats_tables/10_resource_persistent_ids.sql
chalice/chalicelib/api/derived_stats_tables/11_resources.sql
chalice/chalicelib/api/derived_stats_tables/12_resource_evaluations.sql
chalice/chalicelib/api/derived_stats_tables/13_prevous_next_resource_stats.sql
chalice/chalicelib/api/derived_stats_tables/14_previous_next_resource_status_stats.sql

We probably still need to upgrade the RDS instance for production to run these effectively

CT-726b - More efficient stats queries. 

---

build/gulp_helpers/helpers.js
build/gulp_tasks/0.parameters.shared.js
build/gulp_tasks/6.1.environment.cloudfront.js
build/gulp_tasks/6.environment.database.js

Prettier the JS

---

chalice/chalicelib/criteria/aws_s3_secure_policy.py
chalice/tests/chalicelib/criteria/test_aws_s3_secure_policy.py
chalice/tests/chalicelib/criteria/test_data.py

This is the wrong way to solve IAM/bucket policy misconfiguration. We
need an IAM / policy parser we can give a policy, and ask questions of
it. Trying to guess all the conditions which could negate a control is
madness.

Fix and clean up S3 policy tests

---

chalice/chalicelib/templates/components/check_header.html

unrendered links and HTML formatting.

CT-747 - Add safe filter to text components of check header template to fix

---

chalice/chalicelib/api/derived_stats_tables/06.5_daily_resource_count.sql
chalice/chalicelib/api/derived_stats_tables/08.5_monthly_resource_count.sql
chalice/chalicelib/models.py
chalice/chalicelib/routes.py
chalice/chalicelib/template_handler.py
chalice/chalicelib/templates/components/charts/stats_current_account_percent_failure.html
chalice/chalicelib/templates/components/charts/stats_daily_resource_count.html
chalice/chalicelib/templates/components/charts/stats_monthly_resource_count.html
chalice/chalicelib/templates/stats.html

Add derived report tables to be regenerated. 
Add daily and monthly charts to stats endpoint. 
Swap useless existing overview page for new stats page.

CT-813 - Create a metric for the average number of fails/passes/exceptions per account

---

chalice/chalicelib/criteria/aws_ec2_egress_restriction.py
chalice/tests/chalicelib/criteria/test_aws_ec2_egress_restriction.py
chalice/tests/chalicelib/criteria/test_data.py

CT-831 - Correct egress check to pass groups named "default" by exception

---

chalice/chalicelib/admin.py

Quick bit of readability fixes.

reformat criteria_finder()

---

chalice/chalicelib/admin.py
chalice/chalicelib/aws/gds_aws_client.py
chalice/chalicelib/aws/gds_iam_client.py
chalice/chalicelib/demos.py
chalice/chalicelib/models.py
chalice/chalicelib/utilities.py
chalice/requirements.txt
chalice/tests/chalicelib/aws/test_client_default.py
chalice/tests/chalicelib/aws/test_gds_aws_client.py
chalice/tests/chalicelib/aws/test_gds_iam_client.py

This should not be merged until after - CT-802 https://github.com/alphagov/csw-configuration/pull/22 has been merged and applied to production. 
CT-802 merged so this is now ready to go.

CT-803 - Implement lambda to read the access management IAM roles

---

chalice/chalicelib/admin.py

Enabling daily scheduled update.
Last one!

CT-803 - Validated manual team update on production and uat.

---

chalice/chalicelib/api/derived_stats_tables/04_daily_account_stats.sql
chalice/chalicelib/auth.py
chalice/chalicelib/models.py

Added a filter to stop blank entries in user list getting processed 
Added debug logging if a user session fails to update.

CSW-75 - Fix error in daily account stats query following severity filter

---

build/package.json
chalice/chalicelib/admin.py

I got the syntax wrong for the cron'd lambda and I forgot to switch the TF branch back to master.

Correct rate syntax
